# Generated by Django 3.1.3 on 2021-05-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='длина до 210 символов, заполнять необязательно', max_length=210, verbose_name='SEO Title')),
                ('description', models.CharField(blank=True, help_text='длина до 450 символов', max_length=450, verbose_name='SEO Description')),
                ('h1', models.CharField(blank=True, help_text='Описание страницы под заголовком  до 100 символов', max_length=100, verbose_name='Описание страницы')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блог',
            },
        ),
    ]
