# Generated by Django 3.1.3 on 2021-05-13 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.blogpage'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='mini_description',
            field=models.CharField(blank=True, help_text='Описание страницы под заголовком  до 100 символов', max_length=100, verbose_name='Описание страницы'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='h1',
            field=models.CharField(help_text='Заголовок h1 до 100 символов', max_length=100, verbose_name='Заголовок'),
        ),
    ]
