# Generated by Django 3.1.3 on 2021-05-13 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210513_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='mini_description',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='h1',
            field=models.CharField(blank=True, help_text='Описание страницы под заголовком до 100 символов', max_length=100, verbose_name='Описание страницы'),
        ),
        migrations.CreateModel(
            name='CategoryBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='длина до 210 символов, заполнять необязательно', max_length=210, verbose_name='SEO Title')),
                ('description', models.CharField(blank=True, help_text='длина до 450 символов', max_length=450, verbose_name='SEO Description')),
                ('h1', models.CharField(help_text='Заголовок h1 до 100 символов', max_length=100, verbose_name='Заголовок')),
                ('mini_description', models.CharField(blank=True, help_text='Описание страницы под заголовком  до 100 символов', max_length=100, verbose_name='Описание страницы')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.categoryblog')),
            ],
            options={
                'verbose_name': 'Категория блога',
                'verbose_name_plural': 'Категории в блоге',
            },
        ),
    ]
