# Generated by Django 3.1.3 on 2021-05-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_categoryblog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryblog',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='URL-адрес'),
        ),
    ]
